### ISSUE TITLE
AMA Rules

### ISSUE THREAD

**Issue by nathenharvey** [chef-training/open_spaces#1]
I held an AMA at DevOpsDays Belgium and wrote four rules on the flipchart in the room:
- This is a safe space
- No question is off limits
- Anyone may ask a question
- Anyone may answer a question

Seemed to work well, we should probably include this somewhere in our description.  Are 

/cc @burtlo @mary-grace

**Comment by burtlo** [comment]
Sounds like a good thing to add in a pull request.
